### PR TITLE
Bring in Kodi agile to master

### PR DESCRIPTION
**Pull request by AlwinEsch**
This changes can in master after https://github.com/xbmc/xbmc/pull/12148 is merged.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
After the kodi request is approved becomes this cleaned up and changed in one commit.

**Comment by AlwinEsch** [comment]
@notspiff is this style also for you OK?

**Comment by akva2** [comment]
The header paths seems like a regression. Why include kodi in them? And that nasty .. hack is also a bit poo

**Comment by AlwinEsch** [comment]
The hack is really poo, complete right. Currently there to have still old addons compatible.

I have never, never liked the way before with a e.g. `#include "xbmc_pvr_types.h`. This is normally a include of a own header on own sources for me.

The other reason to have `kodi` folder before is to prevent in future include problems. As example comes "Filesystem.h", if now a `#include "Filesystem.h"` is used can a addon developer not use as own header with this name, with `#include <kodi/Filesystem.h>` no problem.

The old header name style with a xbmc or kodi before is for me in case with much more headers not so good.

The next where it is really good to have as "<>" is the auto completion during write of code.

screenshot_20170523_111624

**Comment by akva2** [comment]
use of quote or angles is completely orthogonal as such. the only meaning is which is tested first (quotes mean check source directory, then include paths, angles the other way around).

i'm just tired of the never-ending dance back and forth. i did like you did it, then it was changed to what is now with rebranding ease as the reason.

**Comment by AlwinEsch** [comment]
Has asked on slack to others, this has accepted it with @Rechi @a1rwulf @paxxi and @ksooo.

I think there comes again the discussion like several years ago but what you think, do we try it?

**Comment by akva2** [comment]
As long as there is no reversal again it is all good for my sake. But if we do this and have to change it again i will go loonie tunes ;) @wsnipex is not on the list u mention, he will have an opinion on this.

**Comment by wsnipex** [comment]
Well, this will make rebranding a lot more difficult. It means addons won't build against a fork without sed-ing the includes. And the hack is ugly as shit.

Anyway I'm not a addon maintainer, so feel free to ignore if all relevant devs agree.

**Comment by AlwinEsch** [comment]
For me can a fork with other name stil use "kodi", with the current header names is this already present.

I understand that some forks or complete another Softwares want to use the addons, but with the current header names is it already fixed to "xbmc" or "kodi", this becomes removed and the folder name used as alternative.

The only difficult part can be if someone develop on Kodi and on a fork that it use the same path, but to hold Kodi's addons compatibel with him must he already use equal headers.

**Pull request merged**
